export interface DemoProduct {
  id: string;
  name: string;
  sku: string;
  barcode: string;
  category: "Smartphones" | "Chargers" | "Earbuds" | "Cables" | "Accessories" | "Laptops";
  price: number;
  costPrice: number;
  stock: number;
  minStock: number;
  image: string;
  warranty: string;
  brand: string;
}

export const demoProducts: DemoProduct[] = [
  {
    id: "prod-001",
    name: "Infinix 45W Fast Charger Kit (Type-C)",
    sku: "INF-CHG-45W",
    barcode: "890123456001",
    category: "Chargers",
    price: 1450,
    costPrice: 950,
    stock: 28,
    minStock: 10,
    image: "/images/asset-2.jpg",
    warranty: "6 Months Official",
    brand: "Infinix",
  },
  {
    id: "prod-002",
    name: "Type-C Braided Nylon Cable 1m",
    sku: "CBL-TC-1M",
    barcode: "890123456002",
    category: "Cables",
    price: 350,
    costPrice: 180,
    stock: 65,
    minStock: 20,
    image: "/images/asset-2.jpg",
    warranty: "30 Days Replacement",
    brand: "Baseus",
  },
  {
    id: "prod-003",
    name: "Anker Soundcore R50i True Wireless",
    sku: "ANK-R50I-BLK",
    barcode: "890123456003",
    category: "Earbuds",
    price: 2150,
    costPrice: 1600,
    stock: 14,
    minStock: 5,
    image: "/images/asset-2.jpg",
    warranty: "18 Months Official",
    brand: "Anker",
  },
  {
    id: "prod-004",
    name: "9D Privacy Tempered Glass Protector",
    sku: "PRV-GLS-15P",
    barcode: "890123456004",
    category: "Accessories",
    price: 250,
    costPrice: 80,
    stock: 90,
    minStock: 25,
    image: "/images/asset-2.jpg",
    warranty: "Instant Verification",
    brand: "Gorilla",
  },
  {
    id: "prod-005",
    name: "Samsung Galaxy A15 5G (8GB/128GB)",
    sku: "SM-A156B-DS",
    barcode: "890123456005",
    category: "Smartphones",
    price: 22999,
    costPrice: 20500,
    stock: 9,
    minStock: 3,
    image: "/images/asset-2.jpg",
    warranty: "1 Year Official Brand",
    brand: "Samsung",
  },
  {
    id: "prod-006",
    name: "Xiaomi Redmi Note 13 (6GB/128GB)",
    sku: "RDM-NT13-6G",
    barcode: "890123456006",
    category: "Smartphones",
    price: 19499,
    costPrice: 17200,
    stock: 12,
    minStock: 4,
    image: "/images/asset-2.jpg",
    warranty: "1 Year Official Brand",
    brand: "Xiaomi",
  },
  {
    id: "prod-007",
    name: "Baseus 20W Super Si Fast Adapter",
    sku: "BAS-20W-WHT",
    barcode: "890123456007",
    category: "Chargers",
    price: 950,
    costPrice: 620,
    stock: 42,
    minStock: 15,
    image: "/images/asset-2.jpg",
    warranty: "6 Months Official",
    brand: "Baseus",
  },
  {
    id: "prod-008",
    name: "Realme Buds T110 ANC Earbuds",
    sku: "RLM-T110-WHT",
    barcode: "890123456008",
    category: "Earbuds",
    price: 1850,
    costPrice: 1350,
    stock: 22,
    minStock: 6,
    image: "/images/asset-2.jpg",
    warranty: "6 Months Replacement",
    brand: "Realme",
  },
  {
    id: "prod-009",
    name: "Baseus Cafule Lightning to Type-C 2m",
    sku: "BAS-CL-2M-RED",
    barcode: "890123456009",
    category: "Cables",
    price: 650,
    costPrice: 380,
    stock: 35,
    minStock: 12,
    image: "/images/asset-2.jpg",
    warranty: "30 Days Replacement",
    brand: "Baseus",
  },
  {
    id: "prod-010",
    name: "Apple 20W USB-C Power Adapter (Original)",
    sku: "APL-20W-ORIG",
    barcode: "890123456010",
    category: "Chargers",
    price: 2800,
    costPrice: 2250,
    stock: 18,
    minStock: 5,
    image: "/images/asset-2.jpg",
    warranty: "1 Year Apple Warranty",
    brand: "Apple",
  },
  {
    id: "prod-011",
    name: "Joyroom 10000mAh Power Bank 22.5W",
    sku: "JYR-10K-PB",
    barcode: "890123456011",
    category: "Chargers",
    price: 1650,
    costPrice: 1150,
    stock: 31,
    minStock: 8,
    image: "/images/asset-2.jpg",
    warranty: "6 Months Replacement",
    brand: "Joyroom",
  },
  {
    id: "prod-012",
    name: "Remax OTG Adapter Type-C to USB 3.0",
    sku: "RMX-OTG-U3",
    barcode: "890123456012",
    category: "Accessories",
    price: 180,
    costPrice: 70,
    stock: 80,
    minStock: 20,
    image: "/images/asset-2.jpg",
    warranty: "7 Days Check Warranty",
    brand: "Remax",
  },
];
